### ISSUE TITLE
Include GitHub ribbon on the main page

### ISSUE THREAD

**Issue by SirJosh3917** [SirJosh3917/schedule-an-event#3]
A GitHub ribbon should be included on the main scheduling page, so people can visit the source code easily.

Some information on ribbons [here](https://github.blog/2008-12-19-github-ribbons/).

**Comment by Kashish121** [comment]
Hey, I would like to take this up.

**Comment by SirJosh3917** [comment]
go for it :+1:

**Comment by Kashish121** [comment]
There seems some permission issues with your repository.
![image](https://user-images.githubusercontent.com/56366103/82664812-2b89f680-9c50-11ea-9dce-8a44a48420ed.png)

**Comment by SirJosh3917** [comment]
oh don't worry about that - github actions are currently just being used to allow it so that committed code automatically gets deployed. i think there's some kind of azure actions thing i can do to ensure it only runs on master, i'll look into that after i merge #9

**Comment by SirJosh3917** [comment]
Fixed with the merge of #9 :tada:
